// Do not edit this file directly.
// Instead, edit the `packages/eslint-config/next.config.js` file.
// module.exports = require("@repo/eslint-config/next");
export { default } from "@repo/eslint-config/next";
