name: "Monthly Dependency Update"

on:
    schedule:
        - cron: "0 0 1 * *" # Runs at 00:00 on the 1st of every month
    workflow_dispatch: # Allows manual triggering of the workflow

permissions:
    contents: write
    pull-requests: write

jobs:
    update-dependencies:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: 🏗 Setup monorepo
              uses: ./.github/actions/setup-monorepo

            - name: Run dependency update script
              run: pnpm run deps

            - name: Check for changes
              id: git-check
              run: git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT
              continue-on-error: true

            - name: Create Pull Request
              if: steps.git-check.outputs.changes == 'true'
              uses: peter-evans/create-pull-request@v7
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: "chore: bump deps ⚡️"
                  title: "chore: bump deps ⚡️"
                  body: |
                      Automated monthly dependency update
                      - Bump dependencies to their latest versions.
                      - Auto-generated by [create-pull-request][1]

                      [1]: https://github.com/peter-evans/create-pull-request
                  branch: monthly-deps-update
                  delete-branch: true
                  base: main
