name: Deploy Site

on:
    push:
        branches: [develop, main]
        paths: ["_site/**"]
    pull_request:
        paths: ["_site/**"]
        types: [opened, reopened, auto_merge_enabled]
        branches: [develop]
    workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: macos-latest

    steps:
        - uses: actions/checkout@v4

        - uses: pnpm/action-setup@v4
          with:
              version: 10.2.0

        - uses: actions/setup-node@v4
          with:
              node-version: 22.x
              cache: pnpm

        - name: 📦 Install dependencies
          run: pnpm install --no-frozen-lockfile
          shell: bash

        - name: 🚀 Deploy to Vercel
          run: |
              environment=$([[ "${{ github.ref }}" == 'refs/heads/main' ]] && echo "production" || echo "preview")
              pnpm dlx vercel pull _site --yes --environment=$environment --token=${{ secrets.VERCEL_TOKEN }}
              rm -rf .vercel && mv _site/.vercel .

              pnpm dlx vercel build --token=${{ secrets.VERCEL_TOKEN }}
              pnpm dlx vercel deploy --prebuilt --archive=tgz --token=${{ secrets.VERCEL_TOKEN }}
